apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
  labels:
      {{- include "application-template.labels" . | nindent 4 }}
type: Opaque
data:
  DEEPSEEK_API_KEY: {{ .Values.openai.apiKey | b64enc }}
---

apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  labels:
      {{- include "application-template.labels" . | nindent 4 }}
type: Opaque
data:
  DOCKER_USER: {{ .Values.docker.dockerUser | b64enc }}
  DOCKER_TOKEN: {{ .Values.docker.dockerToken | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.docker.registrySecretName }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "application-template.imagePullSecret" . }}

