### actuator
GET http://localhost:{{application-port}}/actuator
Accept: application/json

### actuator info
GET http://localhost:{{application-port}}/actuator/info
Accept: application/json

### Get Prometheus Metrics
GET http://localhost:{{application-port}}/actuator/prometheus
Accept: application/openmetrics-text;version=1.0.0;charset=utf-8

### Get Prometheus Metrics
GET http://localhost:{{application-port}}/actuator/prometheus
Accept: text/plain;version=0.0.4;charset=utf-8

### actuator health
GET http://localhost:{{application-port}}/actuator/health
Accept: application/json

### actuator health
GET http://localhost:{{application-port}}/actuator/health/readiness
Accept: application/json

### actuator health
GET http://localhost:{{application-port}}/actuator/health/liveness
Accept: application/json

### actuator metrics
GET http://localhost:{{application-port}}/actuator/metrics
Accept: application/json

### actuator metrics
GET http://localhost:{{application-port}}/actuator/metrics/http.client.requests
Accept: application/json

# the ai metrics is only avaialable after the chat client has been called once. make sure to call the chat client first.
### actuator ai metrics
GET http://localhost:{{application-port}}/actuator/metrics/spring.ai.chat.client
Accept: application/json

### actuator ai metrics
GET http://localhost:{{application-port}}/actuator/metrics/spring.ai.chat.client.active
Accept: application/json

### actuator metrics
GET http://localhost:{{application-port}}/actuator/metrics/gen_ai.client.operation
Accept: application/json

### actuator metrics token usage
GET http://localhost:{{application-port}}/actuator/metrics/gen_ai.client.token.usage
Accept: application/json

### actuator metrics
GET http://localhost:{{application-port}}/actuator/metrics/gen_ai.client.operation.active
Accept: application/json

### actuator metrics
GET http://localhost:{{application-port}}/actuator/metrics/gen_ai.client.token.usage
Accept: application/json

### actuator metrics
GET http://localhost:8080/actuator/metrics/gen_ai.client.token.usage?tag=gen_ai.token.type:input
Accept: application/json

### actuator metrics
GET http://localhost:8080/actuator/metrics/gen_ai.client.token.usage?tag=gen_ai.token.type:output
Accept: application/json

### actuator metrics
GET http://localhost:8080/actuator/metrics/gen_ai.client.token.usage?tag=gen_ai.token.type:total
Accept: application/json

### actuator metrics
GET http://localhost:8080/actuator/metrics/gen_ai.client.operation
Accept: application/json

### actuator env
GET http://localhost:{{application-port}}/actuator/env
Accept: application/json

### actuator env
GET http://localhost:{{application-port}}/actuator/configprops
Accept: application/json

### actuator beans
GET http://localhost:{{application-port}}/actuator/beans
Accept: application/json

### actuator caches
GET http://localhost:{{application-port}}/actuator/caches
Accept: application/json

### actuator get loggers
GET http://localhost:{{application-port}}/actuator/loggers
